#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================


source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chown -R "$app": "$install_dir"
chmod -R 750 "$install_dir"

#=================================================
# BUILDING SOURCES AND SETTING UP THE SERVER
#=================================================
ynh_script_progression "Installing dependencies..."

#REMOVEME? ynh_hide_warnings #REMOVEME? ynh_go_install

pushd "$install_dir/"
	export GOPATH="$install_dir/build/go"
	export GOCACHE="$install_dir/build/.cache"
	ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=1 go install github.com/RobBrazier/readflow@latest
popd

#REMOVEME? ynh_go_remove
ynh_safe_rm "$install_dir/build"
ynh_safe_rm "$install_dir/.cache"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown "$app": "$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_logrotate
touch "/var/log/$app/$app.log"
chown "$app": "/var/log/$app/$app.log"

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add $app --description="$app service" --test_status="systemctl show $app.service  -p ActiveState --value | grep -v failed" --log "/var/log/$app/$app.log"
# Disable the service, this is to prevent the service from being triggered at boot time
systemctl disable $app.service --quiet

# Configure the systemd timer
ynh_config_add --template="systemd.timer" --destination="/etc/systemd/system/$app.timer"
systemctl enable $app.timer --quiet
systemctl start $app.timer


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
