#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================


source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

systemctl stop $app.timer
systemctl disable $app.timer --quiet
ynh_config_remove_systemd
ynh_safe_rm "/etc/systemd/system/$app.timer"


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
