#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================



source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R "$app": "$install_dir"
chmod -R 750 "$install_dir"

setfacl -R -m user:$app:rX $database_calibreweb

#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/systemd/system/${app}.service"
yunohost service add $app --description="$app service" --test_status="systemctl show $app.service  -p ActiveState --value | grep -v failed" --log "/var/log/$app/$app.log"
# Disable the service, this is to prevent the service from being triggered at boot time
systemctl disable $app.service --quiet

ynh_restore "/etc/systemd/system/$app.timer"
systemctl enable $app.timer --quiet
systemctl start $app.timer

#=================================================
# RESTORE VARIOUS FILES
#=================================================

### For other apps, the simple way is better:
ynh_restore "/var/log/$app/"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
